# Generated by Django 2.2.5 on 2019-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=2000)),
            ],
        ),
    ]
